print("choisi 3 nombres")
n1 = input()
n2 = input()
n3 = input()
n1 = float(n1)
n2 = float(n2)
n3 = float(n3)
mi = min(n1, n2, n3)
print("le min est "+ str(mi))
ma = max(n1, n2, n3)
print("le max est " + str(ma))