print("donne moi 1 nombre")
n1 = input()
n1 = float(n1)
print("donne moi 1 nombre")
n2 = input()
n2 = float(n2)
print("donne moi 1 nombre")
n3 = input()
n3 = float(n3)
print("donne moi 1 nombre")
n4 = input()
n4 = float(n4)
print("donne moi 1 nombre")
n5 = input()
n5 = float(n5)
somme = n1 + n2 + n3 + n4 + n5
moy = somme / 5
moy = str(moy)
print("la moyenne est " + moy )